name: Load Secrets and env vars

on:
  push:
    branches:
      - main

jobs:
  load_vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SS=${{ secrets.SS }}" >> $GITHUB_ENV
          echo "MSG=${{ vars.MSG }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=$1" >> $GITHUB_ENV
