name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Load Secrets and Vars for Production
        uses: ./.github/workflows/load_secrets.yml
        with:
          environment: production

      - name: Execute Generic Deployment for Production
        uses: ./.github/workflows/deployment.yml
